In [1]:
import random
import time

import pandas as pd
from generate_recipe_task import *
from experiment_classes import WrongIngTest

from together import Together

recipe_df = pd.read_csv("csv/inputs_outputs.csv")

num_steps = [len(row.iloc[5].split('\n')) for i, row in recipe_df.iterrows()]
num_ings = [len(row.iloc[3].split('\n')) for i, row in recipe_df.iterrows()]
recipe_df['num_steps'] = num_steps
recipe_df['num_ings'] = num_ings

long_recipes = recipe_df[recipe_df['num_steps'] >= 5]

long_recipes

,title,ingredients,directions,formatted_ingredients,formatted_ingredient_list,formatted_directions,num_steps,num_ings
0,One Hour Rolls,"[""1 c. milk"", ""2 Tbsp. sugar"", ""1 pkg. dry yea...","[""Put flour into a large mixing bowl."", ""Combi...","milk = Ingredient('m1lk', 'milk', 240, over='t...","ingredients = [milk, sugar, yeast, salt, oil, ...","t1 = Transformation('mix', 'Put flour into a l...",11,7
2,Fresh Strawberry Pie,"[""1 baked pie shell"", ""1 qt. cleaned strawberr...","[""Mix water, cornstarch, sugar and salt in sau...","pieshell = Ingredient('pshl', 'baked pie shell...","ingredients = [pieshell, strawberries, water, ...","t1 = Transformation('mix', 'Mix water, cornsta...",8,9
3,Summer Spaghetti,"[""1 lb. very thin spaghetti"", ""1/2 bottle McCo...","[""Prepare spaghetti per package."", ""Drain."", ""...","spaghetti = Ingredient('SPAG', 'very thin spag...","ingredients = [spaghetti, saladsupreme, zestyi...","t1 = Transformation('boil', 'Prepare spaghetti...",5,4
4,Rhubarb Coffee Cake,"[""1 1/2 c. sugar"", ""1/2 c. butter"", ""1 egg"", ""...","[""Cream sugar and butter."", ""Add egg and beat ...","sugar = Ingredient('sug1', 'sugar', 300, over=...","ingredients = [sugar, butter, egg, buttermilk1...","t1 = Transformation('mix', 'Cream sugar and bu...",6,12
9,Cheeseburger Potato Soup,"[""6 baking potatoes"", ""1 lb. of extra lean gro...","[""Wash potatoes; prick several times with a fo...","potato = Ingredient('POT1', 'baking potatoes',...","ingredients = [potato, beef, butter, milk, sal...","t1 = Transformation('mix', 'Wash potatoes; pri...",16,12
10,Mexican Cookie Rings,"[""1 1/2 c. sifted flour"", ""1/2 tsp. baking pow...","[""Sift flour, baking powder and salt together....","flour = Ingredient('flr1', 'sifted flour', 180...","ingredients = [flour, bpow, salt, butter, suga...","t1 = Transformation('mix', 'Sift flour, baking...",13,10
11,Chicken Divan,"[""1/4 c. margarine"", ""1/4 c. chopped onion (or...","[""Melt margarine in skillet; saute onions and ...","margarine = Ingredient('MARG', 'margarine', 57...","ingredients = [margarine, onion, celery, flour...","t1 = Transformation('fry', 'Melt margarine in ...",10,11
12,Spaghetti Sauce To Can,"[""1/2 bushel tomatoes"", ""1 c. oil"", ""1/4 c. mi...","[""Cook ground or chopped peppers and onions in...","tomatoes = Ingredient('tmt1', 'tomatoes', 1202...","ingredients = [tomatoes, oil, garlic, paste, p...","t1 = Transformation('fry', 'Cook ground or cho...",5,12
13,Taco Salad Chip Dip,"[""8 oz. Ortega taco sauce"", ""8 oz. sour cream""...","[""Mix taco sauce, sour cream and cream cheese....","sauce = Ingredient('sauc', 'Ortega taco sauce'...","ingredients = [sauce, sourcream, creamcheese, ...","t1 = Transformation('mix', 'Mix taco sauce, so...",7,12
15,Reeses Cups(Candy),"[""1 c. peanut butter"", ""3/4 c. graham cracker ...","[""Combine first four ingredients and press in ...","peanut = Ingredient('PB01', 'peanut butter', 2...","ingredients = [peanut, graham, butter, sugar, ...","t1 = Transformation('mix', 'Combine first four...",5,6
16,Buckeye Candy,"[""1 box powdered sugar"", ""8 oz. soft butter"", ...","[""Mix sugar, butter and peanut butter."", ""Roll...","powdered_sugar = Ingredient('PDSG', 'powdered ...","ingredients = [powdered_sugar, butter, peanut_...","t1 = Transformation('mix', 'Mix sugar, butter ...",5,7
17,Prize-Winning Meat Loaf,"[""1 1/2 lb. ground beef"", ""1 c. tomato juice"",...","[""Mix well."", ""Press firmly into an 8 1/2 x 4 ...","groundbeef = Ingredient('gdbf', 'ground beef',...","ingredients = [groundbeef, tomatojuice, oats, ...","t1 = Transformation('mix', 'Mix well.', [groun...",5,9
18,Watermelon Rind Pickles,"[""7 lb. watermelon rind"", ""7 c. sugar"", ""2 c. ...","[""Trim off green and pink parts of watermelon ...","rind = Ingredient('wrnd', 'watermelon rind', 3...","ingredients = [rind, sugar, vinegar, clove_oil...","t1 = Transformation('mix', 'Trim off green and...",12,6
19,Angel Biscuits,"[""5 c. flour"", ""3 Tbsp. sugar"", ""4 tsp. baking...","[""Mix flour, sugar, baking powder, soda and sa...","flour = Ingredient('flr1', 'flour', 600, over=...","ingredients = [flour, sugar, bakingpowder, yea...","t1 = Transformation('mix', 'Mix flour, sugar, ...",6,10
20,Taco-Filled Green Pepper,"[""1 lb. Ground Beef"", ""1 pkg. taco seasoning"",...","[""In a large skillet, brown the ground beef. D...","groundbeef = Ingredient('GDBF', 'Ground Beef',...","ingredients = [groundbeef, tacoseasoning, kidn...","t1 = Transformation('fry', 'Brown the ground b...",8,11
21,Cherry Pizza,"[""2 cans cherry pie mix"", ""1 box deluxe white ...","[""Grease a 9 x 12-inch cake pan."", ""Spread che...","cherrypiemix = Ingredient('CPMX', 'cherry pie ...","ingredients = [cherrypiemix, cakemix, butter, ...","t1 = Transformation('mix', 'Grease a 9 x 12-in...",6,5
22,Quick Peppermint Puffs,"[""8 marshmallows"", ""2 Tbsp. margarine, melted""...","[""Dip marshmallows in melted margarine; roll i...","marshmallows = Ingredient('mshl', 'marshmallow...","ingredients = [marshmallows, margarine, pepper...","t1 = Transformation('mix', 'Dip marshmallows i...",5,6
23,Eggless Milkless Applesauce Cake,"[""3/4 c. sugar"", ""1/2 c. shortening"", ""1 1/2 c...","[""Mix Crisco with applesauce, nuts and raisins...","sugar = Ingredient('sug1', 'granulated sugar',...","ingredients = [sugar, shortening, applesauce, ...","t1 = mix('combine wet base', 'Mix shortening w...",5,12
24,Chicken Funny,"[""1 large whole chicken"", ""2 (10 1/2 oz.) cans...","[""Boil and debone chicken."", ""Put bite size pi...","chicken = Ingredient('chkn', 'whole chicken', ...","ingredients = [chicken, gravy, soup, stuffing,...","t1 = Transformation('boil', 'Boil and debone c...",6,6
25,Chicken Stew,"[""3 lb. chicken, boiled"", ""4 medium potatoes, ...","[""Remove chicken from bone."", ""Use the broth.""...","chicken = Ingredient('chkn', 'chicken', 1361, ...","ingredients = [chicken, potatoes, onions, crea...","t1 = Transformation('mix', 'Remove chicken fro...",5,14
26,Pear-Lime Salad,"[""1 (16 oz.) can pear halves, undrained"", ""1 (...","[""Drain pears, reserving juice."", ""Bring juice...","pears = Ingredient('p001', 'pear halves, undra...","ingredients = [pears, gelatin, creamcheese, le...","t1 = Transformation('stir', 'Drain pears, rese...",10,5
28,Double Cherry Delight,"[""1 (17 oz.) can dark sweet pitted cherries"", ...","[""Drain cherries, measuring syrup."", ""Cut cher...","cherries = Ingredient('CHER', 'dark sweet pitt...","ingredients = [cherries, gingerale, jello, wat...","t1 = Transformation('mix', 'Drain cherries, me...",9,8
31,Quick Barbecue Wings,"[""chicken wings (as many as you need for dinne...","[""Clean wings."", ""Flour and fry until done."", ...","chickenwings = Ingredient('CWNG', 'chicken win...","ingredients = [chickenwings, flour, barbecuesa...","t1 = Transformation('mix', 'Clean wings.', [ch...",8,4
32,Corral Barbecued Beef Steak Strips,"[""2 lb. round steak 1/2 to 3/4-inch thick, sli...","[""Brown strips in cooking oil."", ""Pour off dri...","steak = Ingredient('stk1', 'round steak', 907,...","ingredients = [steak, oil, tomato_sauce, water...","t1 = Transformation('fry', 'Brown strips in co...",5,9
33,No-Bake Nut Cookies,"[""1 c. firmly packed brown sugar"", ""1/2 c. eva...","[""In a heavy 2-quart saucepan, mix brown sugar...","brownsugar = Ingredient('BRSU', 'firmly packed...","ingredients = [brownsugar, evaporatedmilk, van...","t1 = Transformation('mix', 'In a heavy 2-quart...",6,8
37,Strawberry Whatever,"[""1 lb. frozen strawberries in juice"", ""1 smal...","[""Mix Jell-O in boiling water."", ""Add strawber...","strawberries = Ingredient('st01', 'frozen stra...","ingredients = [strawberries, pineapple, banana...","t1 = Transformation('boil', 'Boil water.', [wa...",8,8
38,"Grandma Hanrath'S Banana Breadfort Collins, Co...","[""1 c. sugar"", ""1/2 c. shortening"", ""2 eggs (a...","[""Cream sugar and shortening."", ""Add eggs, sal...","sugar = Ingredient('sug1', 'sugar', 200, over=...","ingredients = [sugar, shortening, eggs, salt, ...","t1 = Transformation('mix', 'Cream sugar and sh...",5,10
39,Jewell Ball'S Chicken,"[""1 small jar chipped beef, cut up"", ""4 boned ...","[""Place chipped beef on bottom of baking dish....","chippedbeef = Ingredient('CBF1', 'chipped beef...","ingredients = [chippedbeef, chickenbreasts, cr...","t1 = Transformation('mix', 'Place chipped beef...",5,6

In [2]:
num_recipes = 10

actor_specs = ["Alice", "She", 1, 0.5, 0]
transcipt_steps = 3
max_recipes = 4

In [3]:
selected_row = long_recipes.iloc[14]
print(f'Generating transcript for {selected_row.iloc[0]}')
generate_task_file_from_row(selected_row, actor_specs, transcipt_steps)
# time.sleep(1)
!python 'recipe_task/recipe_task.py'
# time.sleep(1)
output_text = open("recipe_task/output.txt", "r").read()
print(output_text)

Generating transcript for Taco-Filled Green Pepper
Alice fries the Ground Beef to make some brownedbeef.
She stirs the brownedbeef, taco seasoning, Kidney beans and salsa to make some meatmixture.
Continuing with the recipe, she boils the green peppers to make some parboiledpeppers.

In [4]:
aug_ings = ['10 oz garam masala', '5 cloves star anise']
test = WrongIngTest(output_text, transcipt_steps, selected_row, actor_specs, max_recipes=max_recipes, augmented_ingredients=aug_ings)

model_list = ["OpenAI/gpt-oss-20B",
              "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
              "Qwen/Qwen3-235B-A22B-Instruct-2507-tput",
              "moonshotai/Kimi-K2-Instruct-0905",
              "deepseek-ai/DeepSeek-R1",]

ing_acc = {}
for ing in test.unused_ingredients: ing_acc[ing] = []
overall_acc = []

for model in model_list:
    print(f'Testing {model}:')
    start = time.time()
    test.run_test(client=Together(api_key=''), model=model, n=num_recipes)
    test.print_results(match_exact=False)
    accuracies = test.get_results(match_exact=False)
    print(accuracies)

    print(f'Testing finished: ({'%.2f' % (time.time()-start)} seconds)')
    print('='*50)
    print()

    for i, ing in enumerate(test.unused_ingredients): ing_acc[ing].append(accuracies[i])
    overall_acc.append(sum(accuracies)/len(accuracies))

Testing OpenAI/gpt-oss-20B:
Running recipe with 'onion', spec level 0.
[**********]
Running recipe with 'Tomato', spec level 0.
[**********]
Running recipe with 'cheddar cheese', spec level 0.
[**********]
====================
Expected: Recipe 2
Actual: ['Recipe 3', 'Recipe 3', 'Recipe 4', 'Recipe\xa03', 'Recipe 4', 'Recipe 3', 'Recipe 3', 'Recipe 3', 'Recipe 3', 'Recipe 4']
Accuracy: 0.0
====================
Expected: Recipe 3
Actual: ['Recipe 2', 'Recipe 2', 'Recipe 4', 'Recipe 2', 'Recipe 1', 'Recipe 2', 'Recipe 2', 'Recipe 4', 'Recipe 2', 'Recipe 2']
Accuracy: 0.0
====================
Expected: Recipe 4
Actual: ['Recipe 2', 'Recipe 2', 'Recipe 1', 'Recipe 1', 'Recipe 2', 'Recipe 1', 'Recipe 2', 'Recipe 2', 'Recipe 2', 'Recipe 2']
Accuracy: 0.0
====================
[0.0, 0.0, 0.0]
Testing finished: (428.67 seconds)
==================================================

Testing meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8:
Running recipe with 'onion', spec level 0.
[**********]
Running recipe with 'Tomato', spec level 0.
[**********]
Running recipe with 'cheddar cheese', spec level 0.
[**********]
====================
Expected: Recipe 2

In [5]:
model = 'gpt-5'

print(f'Testing {model}:')
start = time.time()
test.run_test(n=num_recipes)
test.print_results(match_exact=False)
accuracies = test.get_results(match_exact=False)
print(accuracies)

print(f'Testing finished: ({'%.2f' % (time.time()-start)} seconds)')
print('='*50)
print()

model_list.append(model)
for i, ing in enumerate(test.unused_ingredients): ing_acc[ing].append(accuracies[i])
overall_acc.append(sum(accuracies)/len(accuracies))

Testing gpt-5:
Running recipe with 'onion', spec level 0.
[**********]
Running recipe with 'Tomato', spec level 0.
[**********]
Running recipe with 'cheddar cheese', spec level 0.
[**********]
====================
Expected: Recipe 2
Actual: ['Recipe 2', 'Recipe 2', 'Recipe 2', 'Recipe 2', 'Recipe 2', 'Recipe 2', 'Recipe 2', 'Recipe 2', 'Recipe 2', 'Recipe 2']
Accuracy: 1.0
====================
Expected: Recipe 3
Actual: ['Recipe 3', 'Recipe 3', 'Recipe 3', 'Recipe 3', 'Recipe 3', 'Recipe 3', 'Recipe 3', 'Recipe 3', 'Recipe 3', 'Recipe 3']
Accuracy: 1.0
====================
Expected: Recipe 4
Actual: ['Recipe 4', 'Recipe 4', 'Recipe 4', 'Recipe 4', 'Recipe 4', 'Recipe 2', 'Recipe 4', 'Recipe 2', 'Recipe 4', 'Recipe 4']
Accuracy: 0.8
====================
[1.0, 1.0, 0.8]
Testing finished: (648.12 seconds)
==================================================

In [6]:
d = {'model': model_list}
for ing in test.unused_ingredients: d[ing] = ing_acc[ing]
d[f'overall accuracy (n={num_recipes * (max_recipes-1)})'] = overall_acc
df = pd.DataFrame(data=d)
df

,model,onion,Tomato,cheddar cheese,overall accuracy (n=30)
0,OpenAI/gpt-oss-20B,0.0,0.0,0.0,0.000000
1,meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8,0.0,0.0,0.0,0.000000
2,Qwen/Qwen3-235B-A22B-Instruct-2507-tput,0.0,0.0,0.0,0.000000
3,moonshotai/Kimi-K2-Instruct-0905,0.0,0.0,0.1,0.033333
4,deepseek-ai/DeepSeek-R1,0.9,0.7,0.7,0.766667
5,gpt-5,1.0,1.0,0.8,0.933333